version: '3'
services:
  leaderboard:
    build:
      context: .
    depends_on:
      - redis
      - elasticsearch
    environment:
      REDIS_ADDR: redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 6025:6025
    restart: on-failure
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  elasticsearch:
    image: elasticsearch:7.17.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
  kibana:
    image: kibana:7.17.4
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
