name: load-test
on:
  workflow_run:
    workflows: ["build"]
    types: 
      - completed
jobs:
  load-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose up -d --build

    - run: |
        cat << EOF > loadtest-config.yaml
          url: http://localhost:6025
          SLOs:
            http/error-rate: 0
            http/latency-max: 100
            http/latency-mean: 10
            http/latency-p99: 50
        EOF
    - uses: iter8-tools/iter8-action@v1
      with:
        chart: load-test-http
        valuesFile: loadtest-config.yaml

    - name: Stop containers
      if: always()
      run: docker-compose down