name: github-ci
on: [push, pull_request]
jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.48.0
        working-directory: ./source
        args: --config .golangci.yaml

    - name: build
      working-directory: ./source
      run: go build -v ./...

    - name: test
      working-directory: ./source
      run: go test -v ./...
